@echo off
echo Installing @types/jsonwebtoken...
npm install --save-dev @types/jsonwebtoken
echo Adding changes to git...
git add package.json package-lock.json
echo Committing changes...
git commit -m "fix: add @types/jsonwebtoken for TypeScript compilation"
echo Pushing to GitHub...
git push origin main
echo Done! Vercel should now build successfully.
pause
